### ISSUE TITLE
ImportError: No module named pymyair

### ISSUE THREAD

**Issue by mstrelan** [smallsam/pymyair#5]
After running `pip install pymyair` I get the following error when running `myair --help`
```
Traceback (most recent call last):
  File "/usr/local/bin/myair", line 9, in <module>
    load_entry_point('pymyair==0.1.0', 'console_scripts', 'myair')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 542, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2569, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2229, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2235, in resolve
  File "/usr/local/lib/python2.7/dist-packages/pymyair/cli.py", line 6, in <module>
    from pymyair.pymyair import MyAir
ImportError: No module named pymyair
```

**Comment by mstrelan** [comment]
FWIW this is the output from `pip install pymyair`
```
Downloading/unpacking pymyair
  Downloading pymyair-0.1.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/pymyair/setup.py) egg_info for package pymyair
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    zip_safe flag not set; analyzing archive contents...

    Installed /tmp/pip_build_root/pymyair/.eggs/pytest_runner-4.2-py2.7.egg

    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    warning: no files found matching '*.jpg' under directory 'docs'
    warning: no files found matching '*.png' under directory 'docs'
    warning: no files found matching '*.gif' under directory 'docs'
Requirement already satisfied (use --upgrade to upgrade): Click>=6.0 in /usr/local/lib/python2.7/dist-packages (from pymyair)
Installing collected packages: pymyair
  Running setup.py install for pymyair

    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    warning: no files found matching '*.jpg' under directory 'docs'
    warning: no files found matching '*.png' under directory 'docs'
    warning: no files found matching '*.gif' under directory 'docs'
    Installing myair script to /usr/local/bin
  Could not find .egg-info directory in install record for pymyair
Successfully installed pymyair
Cleaning up...
```

**Comment by smallsam** [comment]
Can you paste the output of
which pip
It looks like you might be using a separately installed version of python and not the system default according to some of the paths.

Can you provide some OS version and other environment details?

**Comment by smallsam** [comment]
If you run 
python
Then
import pymyair

Does this succeed?

**Comment by mstrelan** [comment]
```
$ which pip
/usr/local/bin/pip
```

```
$ python
Python 2.7.6 (default, Nov 23 2017, 15:49:48)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymyair
>>>
```
I'm running python on [WSL / Bash on Ubuntu on Windows](https://github.com/Microsoft/WSL) so that could well be related to my issue. But I'm able to run other python apps just fine so I think it should work.

```
$ uname -a
Linux Michael-PC 4.4.0-17134-Microsoft #112-Microsoft Thu Jun 07 22:57:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
```
